name: Platform Add-ons Deployment

on:
  push:
    branches:
      - main
    paths:
      - "helm-values/**"   # only trigger if values change
  workflow_dispatch:       # allow manual runs

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: my-multi-tenant-cluster

jobs:
  helm-addons:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.0"

      - name: Get kubeconfig from EKS
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Add Helm repos
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add policy-reporter https://kyverno.github.io/policy-reporter
          helm repo update

      - name: Helm Diff & Upgrade/Add-ons
        run: |
          # KYVERNO
          helm diff upgrade kyverno kyverno/kyverno --namespace kyverno --install || true
          helm upgrade --install kyverno kyverno/kyverno --namespace kyverno --create-namespace -f helm-values/kyverno-values.yaml

          # GRAFANA
          helm diff upgrade grafana grafana/grafana --namespace monitoring --install -f helm-values/grafana-values.yaml || true
          helm upgrade --install grafana grafana/grafana --namespace monitoring --create-namespace -f helm-values/grafana-values.yaml

          # PROMETHEUS
          helm diff upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --install -f helm-values/prometheus-values.yaml || true
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace -f helm-values/prometheus-values.yaml

          # POLICY REPORTER
          helm diff upgrade policy-reporter policy-reporter/policy-reporter --namespace policy-reporter --install -f helm-values/policy-reporter-values.yaml || true
          helm upgrade --install policy-reporter policy-reporter/policy-reporter --namespace policy-reporter --create-namespace -f helm-values/policy-reporter-values.yaml
